version: "3.1"

services:
  face_eye:
    image: face_eye
    build: .
    ports: ["8000:8000"]
    command: 'bash -c "cd /home/FaceEye/ && \
              python manage.py makemigrations && \
              python manage.py migrate && \
              uwsgi /home/FaceEye/face_eye/face_eye_uwsgi.ini"'
    depends_on:
     - redis
     - mysql2redis1

  redis:
    image: redis
    ports: ["6379"]

  mysql2redis1:
    image: vanjaydo/mysql2redis
    build: ./mysql2redis
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: face_eye


