version: "3"

services:
  face_eye:
    image: vanjaydo/face-eye
    ports: ["8000:8000"]
    volumes: [".:/mnt"]
    command: "bash /mnt/run_face_eye.sh"
    depends_on:
     - redis
     - mysql2redis

  redis:
    image: redis

  mysql2redis:
    build: ./docker-mysql2redis
    volumes: [".:/mnt"]
    environment:
      MYSQL_ROOT_PASSWORD: 123456


